version: "3"
services:
  frontend-server:
    image: thetiptop2023667/tiptopfront:latest
    ports:
      - "4200:4200"      
    networks:
      - springmysql-net
    depends_on:
      - mysqldb
  backend-server:
    image: thetiptop2023667/tiptopback:latest
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.username=root
      - spring.datasource.password=HelloWorld123**
      - spring.datasource.url=jdbc:mysql://localhost:3306/tiptopdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=HelloWorld123**
      - MYSQL_DATABASE=tiptopdb
      

networks:
  springmysql-net:
